<?php

//detail pages blocks
if (function_exists('acf_add_local_field_group')) :

    //regular detail blocks
    // NOT FOR CONTENT PAGES
    acf_add_local_field_group([
        'key' => 'detail_content',
        'title' => 'Content pagina',
        'fields' => [
            [
                'key' => 'detail_content_blocks',
                'label' => 'Blokken',
                'name' => 'detail_content_blocks',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layouts' => [
                    'header_block' => [
                        'key' => 'header_block',
                        'name' => 'header_block',
                        'label' => 'Header blok',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'header_block_text',
                                'label' => 'Hoofdtekst',
                                'name' => 'header_block_text',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'header_block_switch',
                                'label' => 'Ronddraaiende knop?',
                                'name' => 'header_block_switch',
                                'type' => 'true_false',
                                'ui' => 1,
                                'ui_on_text' => 'Met knop',
                                'ui_off_text' => 'Zonder knop',
                            ],
                            [
                                'key' => 'header_block_link',
                                'label' => 'link tekst',
                                'name' => 'header_block_link',
                                'type' => 'link',
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'header_block_switch',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'header_image_block' => [
                        'key' => 'header_image_block',
                        'name' => 'header_image_block',
                        'label' => 'Header blok met afbeelding',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'header_image_block_text',
                                'label' => 'Hoofdtekst',
                                'name' => 'header_image_block_text',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'header_image_block_switch',
                                'label' => 'Ronddraaiende knop?',
                                'name' => 'header_image_block_switch',
                                'type' => 'true_false',
                                'ui' => 1,
                                'ui_on_text' => 'Met knop',
                                'ui_off_text' => 'Zonder knop',
                            ],
                            [
                                'key' => 'header_image_block_link',
                                'label' => 'link tekst',
                                'name' => 'header_image_block_link',
                                'type' => 'link',
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'header_image_block_switch',
                                            'operator' => '==',
                                            'value' => '1',
                                        ),
                                    ),
                                ),
                            ],
                            [
                                'key' => 'header_image_block_image',
                                'label' => 'Afbeelding',
                                'name' => 'header_image_block_image',
                                'type' => 'image',
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'intro_block' => [
                        'key' => 'intro_block',
                        'name' => 'intro_block',
                        'label' => 'Intro block',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'intro_text_header_element',
                                'label' => 'intro text header element',
                                'name' => 'intro_text_header_element',
                                'type' => 'button_group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'h1',
                                    'h2' => 'h2',
                                    'h3' => 'h3',
                                    'strong' => 'bold',
                                ],
                                'allow_null' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ],
                            [
                                'key' => 'intro_text_header',
                                'label' => 'Header text',
                                'name' => 'intro_text_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'intro_text_bodytext',
                                'label' => 'Bodytext',
                                'name' => 'intro_text_bodytext',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                                'toolbar' => 'basic',
                            ],
                            [
                                'key' => 'intro_link_repeater',
                                'label' => 'Link repeater',
                                'name' => 'intro_link_repeater',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => '',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Nieuwe link toevoegen',
                                'sub_fields' => [
                                    [
                                        'key' => 'intro_link',
                                        'label' => 'Link',
                                        'name' => 'intro_link',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'delay' => 0,
                                    ],
                                ],
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'pro_con_block' => [
                        'key' => 'pro_con_block',
                        'name' => 'pro_con_block',
                        'label' => 'Pro-con block',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'pro_con_block_header',
                                'label' => 'Headertext',
                                'name' => 'pro_con_block_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'pro_con_block_header_element',
                                'label' => 'intro text header element',
                                'name' => 'pro_con_block_header_element',
                                'type' => 'button_group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'h1',
                                    'h2' => 'h2',
                                    'h3' => 'h3',
                                    'strong' => 'bold',
                                ],
                                'allow_null' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ],
                            [
                                'key' => 'pro_con_block_paragraph',
                                'label' => 'Paragraaf',
                                'name' => 'pro_con_block_paragraph',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'pro_con_block_repeater_pro_header',
                                'label' => 'Heading links',
                                'name' => 'pro_con_block_repeater_pro_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'pro_con_block_repeater_con_header',
                                'label' => 'Heading rechts',
                                'name' => 'pro_con_block_repeater_con_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'pro_con_repeater',
                                'label' => 'Pro & Deliverable repeater',
                                'name' => 'pro_con_repeater',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => '',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'layout' => 'table',
                                'button_label' => 'Nieuw item toevoegen',
                                'sub_fields' => [
                                    [
                                        'key' => 'pro_con_block_pro',
                                        'label' => 'Voordeel',
                                        'name' => 'pro_con_block_pro',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'delay' => 0,
                                    ],
                                    [
                                        'key' => 'pro_con_block_deliverable',
                                        'label' => 'Deliverable',
                                        'name' => 'pro_con_block_deliverable',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'delay' => 0,
                                    ],
                                ],
                            ],
                            [
                                'key' => 'pro_con_block_button',
                                'label' => 'Knop',
                                'name' => 'pro_con_block_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'pro_con_block_investment_header',
                                'label' => 'Investering header',
                                'name' => 'pro_con_block_investment_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'pro_con_block_investment_bodytext',
                                'label' => 'Investering bodytext',
                                'name' => 'pro_con_block_investment_bodytext',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'awards_and_partnerships_block' => [
                        'key' => 'awards_and_partnerships_block',
                        'name' => 'awards_and_partnerships_block',
                        'label' => 'Awards & Partnerships',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'awards_and_partnerships_element',
                                'label' => 'text header element',
                                'name' => 'awards_and_partnerships_element',
                                'type' => 'button_group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'h1',
                                    'h2' => 'h2',
                                    'h3' => 'h3',
                                    'strong' => 'bold',
                                ],
                                'allow_null' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ],
                            [
                                'key' => 'awards_and_partnerships_header',
                                'label' => 'Header text',
                                'name' => 'awards_and_partnerships_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'awards_and_partnerships_gallery',
                                'label' => 'Galerij',
                                'name' => 'awards_and_partnerships_gallery',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'title_gallery_block' => [
                        'key' => 'title_gallery_block',
                        'name' => 'title_gallery_block',
                        'label' => 'Titel & Gallerij',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'title_gallery_title',
                                'label' => 'Title text',
                                'name' => 'title_gallery_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'title_gallery_header',
                                'label' => 'Header text',
                                'name' => 'title_gallery_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'title_gallery_subheader',
                                'label' => 'Subheader text',
                                'name' => 'title_gallery_subheader',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'gallery_image_small',
                                'label' => 'Small image',
                                'name' => 'gallery_image_small',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'gallery_image_medium',
                                'label' => 'Medium image',
                                'name' => 'gallery_image_medium',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'gallery_image_large',
                                'label' => 'Large image',
                                'name' => 'gallery_image_large',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'paragraph_block' => [
                        'key' => 'paragraph_block',
                        'name' => 'paragraph_block',
                        'label' => 'Paragraaf',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'paragraph_block_wysiwyg',
                                'label' => 'Paragraaf',
                                'name' => 'paragraph_block_wysiwyg',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'hubspot_form_block' => [
                        'key' => 'hubspot_form_block',
                        'name' => 'hubspot_form_block',
                        'label' => 'Hubspot formulier',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'hubspot_form_block_title',
                                'label' => 'Titel',
                                'name' => 'hubspot_form_block_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'hubspot_form_block_bodytext',
                                'label' => 'Bodytext',
                                'name' => 'hubspot_form_block_bodytext',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'content_image_block' => [
                        'key' => 'content_image_block',
                        'name' => 'content_image_block',
                        'label' => 'Content & Image',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'content_image_switch',
                                'label' => 'Links / Rechts',
                                'name' => 'content_image_switch',
                                'type' => 'true_false',
                                'ui' => 1,
                                'ui_on_text' => 'Afbeelding rechts / content links',
                                'ui_off_text' => 'Afbeelding links / content rechts',
                            ],
                            [
                                'key' => 'content_image_small',
                                'label' => 'Kleine afbeelding',
                                'name' => 'content_image_small',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'content_image_medium',
                                'label' => 'Medium afbeelding',
                                'name' => 'content_image_medium',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'content_image_block_title',
                                'label' => 'Titel tekst',
                                'name' => 'content_image_block_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'content_image_header_element',
                                'label' => 'Text header element',
                                'name' => 'content_image_header_element',
                                'type' => 'button_group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'h1',
                                    'h2' => 'h2',
                                    'h3' => 'h3',
                                    'strong' => 'bold',
                                ],
                                'allow_null' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ],
                            [
                                'key' => 'content_image_header',
                                'label' => 'Header text',
                                'name' => 'content_image_header',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'content_image_bodytext',
                                'label' => 'Bodytext',
                                'name' => 'content_image_bodytext',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                                'toolbar' => 'basic',
                            ],
                            [
                                'key' => 'content_image_link_repeater',
                                'label' => 'Link repeater',
                                'name' => 'content_image_link_repeater',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => '',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Nieuwe link toevoegen',
                                'sub_fields' => [
                                    [
                                        'key' => 'content_image_repeater_link',
                                        'label' => 'Link',
                                        'name' => 'content_image_repeater_link',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'delay' => 0,
                                    ],
                                ],
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'link_block' => [
                        'key' => 'link_block',
                        'name' => 'link_block',
                        'label' => 'Link',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'link_block_anchor',
                                'label' => 'Link',
                                'name' => 'link_block_anchor',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'team_block' => [
                        'key' => 'team_block',
                        'name' => 'team_block',
                        'label' => 'Team',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'team_block_title',
                                'label' => 'Titel',
                                'name' => 'team_block_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'team_block_btn',
                                'label' => 'Button',
                                'name' => 'team_block_btn',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'team_block_members',
                                'label' => 'Selecteer teamleden',
                                'name' => 'team_block_members',
                                'type' => 'relationship',
                                'post_type' => 'teammembers',
                                'filters' => array('search', 'taxonomy'),
                                'elements' => array('featured_image'),
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'min' => 0,
                                'max' => 999,
                                'default_value' => '',
                                'delay' => '',
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'cta_block' => [
                        'key' => 'cta_block',
                        'name' => 'cta_block',
                        'label' => 'CTA',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'cta_block_img',
                                'label' => 'Afbeelding',
                                'name' => 'cta_block_img',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => 'cta_block_title',
                                'label' => 'Titel',
                                'name' => 'cta_block_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'cta_block_subtitle',
                                'label' => 'Subtitel',
                                'name' => 'cta_block_subtitle',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                            [
                                'key' => 'cta_block_button',
                                'label' => 'Button',
                                'name' => 'cta_block_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'accordion_block' => [
                        'key' => 'accordion_block',
                        'name' => 'accordion_block',
                        'label' => 'Accordion',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'accordion_repeater',
                                'label' => 'Accordion repeater',
                                'name' => 'accordion_repeater',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => '',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => 'Nieuwe accordion toevoegen',
                                'sub_fields' => [
                                    [
                                        'key' => 'accordion_title',
                                        'label' => 'Titel',
                                        'name' => 'accordion_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ],
                                    [
                                        'key' => 'accordion_textarea',
                                        'label' => 'Tekstgebied',
                                        'name' => 'accordion_textarea',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ],
                                ],
                            ],
                            [
                                'key' => 'number_listing_button',
                                'label' => 'Button',
                                'name' => 'number_listing_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'image_block' => [
                        'key' => 'image_block',
                        'name' => 'image_block',
                        'label' => 'Afbeelding',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'image_block_img',
                                'label' => 'Afbeelding',
                                'name' => 'image_block_img',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'quote_block' => [
                        'key' => 'quote_block',
                        'name' => 'quote_block',
                        'label' => 'Quote',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'quote_block_quote',
                                'label' => 'Quote',
                                'name' => 'quote_block_quote',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 0,
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'number_listing_block' => [
                        'key' => 'number_listing_block',
                        'name' => 'number_listing_block',
                        'label' => 'Number listing',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'number_listing_title',
                                'label' => 'Titel',
                                'name' => 'number_listing_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 0,
                                'delay' => 0,
                            ],
                            [
                                'key' => 'number_listing_button',
                                'label' => 'Button',
                                'name' => 'number_listing_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                    'contact_form_block' => [
                        'key' => 'contact_form_block',
                        'name' => 'contact_form_block',
                        'label' => 'Contactformulier',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => 'contact_form_block_shortcode',
                                'label' => 'Contactformulier',
                                'name' => 'contact_form_block_shortcode',
                                'type' => 'text',
                                'instructions' => 'Plaats hier de shortcode van het contactformulier',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 0,
                                'delay' => 0,
                            ],
                        ],
                        'min' => '',
                        'max' => '',
                    ],
                ],
                'button_label' => 'Nieuw blok',
                'min' => '',
                'max' => '',
            ],
        ],
        'location' => [
            // [
            //     [
            //         'param' => 'page_template',
            //         'operator' => '==',
            //         'value' => 'page-content.php',
            //     ],
            // ],
            // [
            //     [
            //         'param' => 'page_template',
            //         'operator' => '==',
            //         'value' => 'page-contact.php',
            //     ],
            // ],
            // [
            //     [
            //         'param' => 'post_type',
            //         'operator' => '==',
            //         'value' => 'post',
            //     ],
            // ],
            // [
            //     [
            //         'param' => 'post_type',
            //         'operator' => '==',
            //         'value' => 'careers',
            //     ],
            // ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ]);
endif;
