<?php
// Headers blocks
if (function_exists('acf_add_local_field_group')):
    //header blocks
    acf_add_local_field_group([
        'key' => 'header',
        'title' => 'Header',
        'fields' => [
            [
                'key' => 'headers',
                'label' => 'Header',
                'name' => 'headers',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layouts' => [
                    // 01_header
                    '01_header' => [
                        'key' => '01_header',
                        'label' => '001 - Header',
                        'name' => '01_header',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => '01_header_layout',
                                'label' => 'Layout',
                                'name' => '01_header_layout',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'image_left' => 'Image Left',
                                    'image_right' => 'Image Right',
                                ],
                                'default_value' => 'image_right',
                                'wrapper' => [
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                            [
                                'key' => '01_header_image',
                                'label' => 'Image',
                                'name' => '01_header_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ],
                            [
                                'key' => '01_header_title',
                                'label' => 'Title',
                                'name' => '01_header_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Title',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '01_header_title_type',
                                'label' => 'Title Type',
                                'name' => '01_header_title_type',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'H1',
                                    'h2' => 'H2',
                                    'h3' => 'H3',
                                    'h4' => 'H4',
                                    'h5' => 'H5',
                                    'h6' => 'H6',
                                    'div' => 'DIV',
                                    'p' => 'P',
                                    'span' => 'SPAN',
                                ],
                                'default_value' => 'div',
                            ],
                            [
                                'key' => '01_header_textarea',
                                'label' => 'Textarea',
                                'name' => '01_header_textarea',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Textarea',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '01_header_button',
                                'label' => 'Button',
                                'name' => '01_header_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Button',
                                'delay' => 0,
                            ],
                            [
                                'key' => '01_header_padding_topbottom',
                                'label' => 'Padding Top/Bottom',
                                'name' => '01_header_padding_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'padding0' => '0px',
                                    'padding20' => '20px',
                                    'padding40' => '40px',
                                    'padding60' => '60px',
                                    'padding80' => '80px',
                                    'padding100' => '100px',
                                    'padding120' => '120px',
                                    'padding160' => '160px',
                                    'padding200' => '200px',
                                ],
                                'default_value' => 'padding40',
                            ],
                            [
                                'key' => '01_header_margin_topbottom',
                                'label' => 'Margin Top/Bottom',
                                'name' => '01_header_margin_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'margin0' => '0px',
                                    'margin20' => '20px',
                                    'margin40' => '40px',
                                    'margin60' => '60px',
                                    'margin80' => '80px',
                                    'margin100' => '100px',
                                    'margin120' => '120px',
                                    'margin160' => '160px',
                                    'margin200' => '200px',
                                ],
                                'default_value' => 'margin40',
                            ],
                        ],
                    ],
                    // 02_header
                    '02_header' => [
                        'key' => '02_header',
                        'label' => '002 - Header',
                        'name' => '02_header',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => '02_header_image',
                                'label' => 'Image',
                                'name' => '02_header_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ],
                            [
                                'key' => '02_header_title_sub',
                                'label' => 'SubTitle',
                                'name' => '02_header_title_sub',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'SubTitle',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '02_header_title',
                                'label' => 'Title',
                                'name' => '02_header_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Title',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '02_header_title_type',
                                'label' => 'Title Type',
                                'name' => '02_header_title_type',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'H1',
                                    'h2' => 'H2',
                                    'h3' => 'H3',
                                    'h4' => 'H4',
                                    'h5' => 'H5',
                                    'h6' => 'H6',
                                    'div' => 'DIV',
                                    'p' => 'P',
                                    'span' => 'SPAN',
                                ],
                                'default_value' => 'div',
                            ],
                            [
                                'key' => '02_header_textarea_left',
                                'label' => 'Textarea Left',
                                'name' => '02_header_textarea_left',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Textarea Left',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '02_header_textarea_right',
                                'label' => 'Textarea Right',
                                'name' => '02_header_textarea_right',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Textarea Right',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '02_header_button',
                                'label' => 'Button',
                                'name' => '02_header_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Button',
                                'delay' => 0,
                            ],
                            [
                                'key' => '02_header_padding_topbottom',
                                'label' => 'Padding Top/Bottom',
                                'name' => '02_header_padding_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'padding0' => '0px',
                                    'padding20' => '20px',
                                    'padding40' => '40px',
                                    'padding60' => '60px',
                                    'padding80' => '80px',
                                    'padding100' => '100px',
                                    'padding120' => '120px',
                                    'padding160' => '160px',
                                    'padding200' => '200px',
                                ],
                                'default_value' => 'padding40',
                            ],
                            [
                                'key' => '02_header_margin_topbottom',
                                'label' => 'Margin Top/Bottom',
                                'name' => '02_header_margin_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'margin0' => '0px',
                                    'margin20' => '20px',
                                    'margin40' => '40px',
                                    'margin60' => '60px',
                                    'margin80' => '80px',
                                    'margin100' => '100px',
                                    'margin120' => '120px',
                                    'margin160' => '160px',
                                    'margin200' => '200px',
                                ],
                                'default_value' => 'margin40',
                            ],
                        ],
                    ],
                    // 03_header
                    '03_header' => [
                        'key' => '03_header',
                        'label' => '003 - Header',
                        'name' => '03_header',
                        'display' => 'block',
                        'sub_fields' => [
                            [
                                'key' => '03_header_topbar_bg_transparent',
                                'label' => 'Topbar Background',
                                'name' => '03_header_topbar_bg_transparent',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'background' => 'Background',
                                    'transparent' => 'Transparent',
                                ],
                                'default_value' => 'background',
                            ],
                            [
                                'key' => '03_header_layout',
                                'label' => 'Layout',
                                'name' => '03_header_layout',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'text_block_left' => 'Text Block Left',
                                    'text_block_right' => 'Text Block Right',
                                ],
                                'default_value' => 'text_block_left',
                                'wrapper' => [
                                    'width' => '100',
                                    'class' => '',
                                    'id' => '',
                                ],
                            ],
                            [
                                'key' => '03_header_image',
                                'label' => 'Image',
                                'name' => '03_header_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'return_format' => 'array',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ],
                            [
                                'key' => '03_header_title',
                                'label' => 'Title',
                                'name' => '03_header_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Title',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '03_header_title_type',
                                'label' => 'Title Type',
                                'name' => '03_header_title_type',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'h1' => 'H1',
                                    'h2' => 'H2',
                                    'h3' => 'H3',
                                    'h4' => 'H4',
                                    'h5' => 'H5',
                                    'h6' => 'H6',
                                    'div' => 'DIV',
                                    'p' => 'P',
                                    'span' => 'SPAN',
                                ],
                                'default_value' => 'div',
                            ],
                            [
                                'key' => '03_header_textarea',
                                'label' => 'Textarea',
                                'name' => '03_header_textarea',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Textarea',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                                'delay' => 0,
                            ],
                            [
                                'key' => '03_header_button',
                                'label' => 'Button',
                                'name' => '03_header_button',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => 'Button',
                                'delay' => 0,
                            ],
                            [
                                'key' => '03_header_padding_topbottom',
                                'label' => 'Padding Top/Bottom',
                                'name' => '03_header_padding_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'padding0' => '0px',
                                    'padding20' => '20px',
                                    'padding40' => '40px',
                                    'padding60' => '60px',
                                    'padding80' => '80px',
                                    'padding100' => '100px',
                                    'padding120' => '120px',
                                    'padding160' => '160px',
                                    'padding200' => '200px',
                                ],
                                'default_value' => 'padding40',
                            ],
                            [
                                'key' => '03_header_margin_topbottom',
                                'label' => 'Margin Top/Bottom',
                                'name' => '03_header_margin_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'choices' => [
                                    'margin0' => '0px',
                                    'margin20' => '20px',
                                    'margin40' => '40px',
                                    'margin60' => '60px',
                                    'margin80' => '80px',
                                    'margin100' => '100px',
                                    'margin120' => '120px',
                                    'margin160' => '160px',
                                    'margin200' => '200px',
                                ],
                                'default_value' => 'margin40',
                            ],
                        ],
                    ],
                ],
                'button_label' => 'Nieuw blok',
                'min' => '',
                'max' => '',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-default-fullwidth.php'
                ],
            ],
        ],
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ]);
endif;