<?php
if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group([
        'key' => 'single_page',
        'title' => 'Single page',
        'fields' => [
            [
                'key' => 'single_blocks',
                'label' => 'Blokken',
                'name' => 'single_blocks',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'layouts' => [
                    // 02_single_title_intro_in_column
                    '02_single_title_intro_in_column' => [
                        'key' => '02_single_title_intro_in_column',
                        'name' => '02_single_title_intro_in_column',
                        'label' => '02 - Single Title Intro Column',
                        'display' => 'block',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => [
                            [
                                'key' => '02_single_title_intro_in_column_title',
                                'label' => 'Title',
                                'name' => '02_single_title_intro_in_column_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                            ],
                            [
                                'key' => '02_single_title_intro_in_column_intro',
                                'label' => 'Intro',
                                'name' => '02_single_title_intro_in_column_intro',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                            ],
                            [
                                'key' => '02_single_title_intro_in_column_intro_text',
                                'label' => 'Intro Text',
                                'name' => '02_single_title_intro_in_column_intro_text',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => [
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'default_value' => '',
                            ],
                            [
                                'key' => '02_single_padding_topbottom',
                                'label' => 'Padding Top/Bottom',
                                'name' => '02_single_padding_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'padding0' => '0px',
                                    'padding20' => '20px',
                                    'padding40' => '40px',
                                    'padding60' => '60px',
                                    'padding80' => '80px',
                                    'padding100' => '100px',
                                    'padding120' => '120px',
                                    'padding160' => '160px',
                                    'padding200' => '200px',
                                ],
                                'default_value' => 'padding40',
                            ],
                            [
                                'key' => '02_single_margin_topbottom',
                                'label' => 'Margin Top/Bottom',
                                'name' => '02_single_margin_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'margin0' => '0px',
                                    'margin20' => '20px',
                                    'margin40' => '40px',
                                    'margin60' => '60px',
                                    'margin80' => '80px',
                                    'margin100' => '100px',
                                    'margin120' => '120px',
                                    'margin160' => '160px',
                                    'margin200' => '200px',
                                ],
                                'default_value' => 'margin40',
                            ],
                        ],
                    ],
                    // 03_single_content
                    '03_single_content' => [
                        'key' => '03_single_content',
                        'name' => '03_single_content',
                        'label' => '03 - Single Content',
                        'display' => 'block',
                        'min' => '',
                        'max' => '',
                        'sub_fields' => [
                            [
                                'key' => '03_single_content_sections',
                                'label' => 'Single Content Sections',
                                'name' => '03_single_content_sections',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => '',
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => '',
                                'max' => '',
                                'layout' => 'row',
                                'button_label' => 'Add new Section',
                                'sub_fields' => [
                                    [
                                        'key' => '03_single_content_type',
                                        'label' => 'Content Type',
                                        'name' => '03_single_content_type',
                                        'type' => 'select',
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                        'return_format' => 'value',  // 'array' || 'label'
                                        'choices' => [
                                            'contentblock' => "Content Block",
                                            'image' => "Image",
                                            'video' => "Video",
                                            'contact' => "Contact Form",
                                        ],
                                        'default_value' => 'standard',
                                    ],
                                    [
                                        'key' => '03_single_content_block_title',
                                        'label' => 'Title',
                                        'name' => '03_single_content_block_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contentblock',
                                                ),
                                            ),
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ],
                                    [
                                        'key' => '03_single_content_block_title_type',
                                        'label' => 'Title Type',
                                        'name' => '03_single_content_block_title_type',
                                        'type' => 'button_group',
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                        'return_format' => 'value',
                                        'layout' => 'horizontal',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contentblock',
                                                ),
                                            ),
                                        ),
                                        'choices' => [
                                            'h1' => 'H1',
                                            'h2' => 'H2',
                                            'h3' => 'H3',
                                            'h4' => 'H4',
                                            'h5' => 'H5',
                                            'h6' => 'H6',
                                            'div' => 'DIV',
                                            'p' => 'P',
                                            'span' => 'SPAN',
                                        ],
                                        'default_value' => 'div',
                                    ],
                                    [
                                        'key' => '03_single_content_block_textarea',
                                        'label' => 'Textarea',
                                        'name' => '03_single_content_block_textarea',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contentblock',
                                                ),
                                            ),
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ],
                                    [
                                        'key' => '03_single_content_block_list_button',
                                        'label' => 'Title Type',
                                        'name' => '03_single_content_block_list_button',
                                        'type' => 'button_group',
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                        'return_format' => 'value',
                                        'layout' => 'horizontal',
                                        'conditional_logic' => array(                            
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contentblock',
                                                ),
                                            ),
                                        ),
                                        'choices' => [
                                            'none' => 'None',
                                            'button' => 'Button',
                                            'list' => 'List',
                                        ],
                                        'default_value' => 'button',
                                    ],
                                    [
                                        'key' => '03_single_content_block_button',
                                        'label' => 'Button',
                                        'name' => '03_single_content_block_button',
                                        'type' => 'link',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_block_list_button',
                                                    'operator' => '==',
                                                    'value' => 'button',
                                                ),
                                            ),
                                        ),
                                    ],
                                    [
                                        'key' => '03_single_content_block_list_type',
                                        'label' => 'List Type',
                                        'name' => '03_single_content_block_list_type',
                                        'type' => 'button_group',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_block_list_button',
                                                    'operator' => '==',
                                                    'value' => 'list',
                                                ),
                                            ),
                                        ),
                                        'choices' => [
                                            'one-columns' => '1 Column',
                                            'two-columns' => '2 Columns',
                                        ],
                                    ],
                                    [
                                        'key' => '03_single_content_block_list',
                                        'label' => 'List',
                                        'name' => '03_single_content_block_list',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_block_list_button',
                                                    'operator' => '==',
                                                    'value' => 'list',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => 'Add new List',
                                        'sub_fields' => [
                                            [
                                                'key' => '03_single_content_block_list_link',
                                                'label' => 'Button',
                                                'name' => '03_single_content_block_list_link',
                                                'type' => 'link',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => [
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ],
                                                'default_value' => 'Button',
                                                'delay' => 0,
                                            ],
                                        ],
                                    ],
                                    [
                                        'key' => '03_single_image',
                                        'label' => 'Image',
                                        'name' => '03_single_image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'image',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'return_format' => 'array',
                                        'preview_size' => 'thumbnail',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ],
                                    [
                                        'key' => '03_single_video_type',
                                        'label' => 'Single Type',
                                        'name' => '03_single_video_type',
                                        'type' => 'button_group',
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                        'return_format' => 'value',
                                        'layout' => 'horizontal',
                                        'conditional_logic' => array(                            
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'video',
                                                ),
                                            ),
                                        ),
                                        'choices' => [
                                            'youtube' => 'Youtube',
                                            'vimeo' => 'Vimeo',
                                        ],
                                        'default_value' => 'youtube',
                                    ],
                                    [
                                        'key' => '03_single_video_youtube',
                                        'label' => 'Youtube video',
                                        'name' => '03_single_video_youtube',
                                        'type' => 'text',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_video_type',
                                                    'operator' => '==',
                                                    'value' => 'youtube',
                                                ),
                                            ),
                                        ),
                                        'default_value' => '',
                                    ],
                                    [
                                        'key' => '03_single_video_vimeo',
                                        'label' => 'Vimeo video',
                                        'name' => '03_single_video_vimeo',
                                        'type' => 'text',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_video_type',
                                                    'operator' => '==',
                                                    'value' => 'vimeo',
                                                ),
                                            ),
                                        ),
                                        'default_value' => '',
                                    ],
                                    [
                                        'key' => '03_single_contact_title',
                                        'label' => 'Title',
                                        'name' => '03_single_contact_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contact',
                                                ),
                                            ),
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ],
                                    [
                                        'key' => '03_single_contact_title_type',
                                        'label' => 'Title Type',
                                        'name' => '03_single_contact_title_type',
                                        'type' => 'button_group',
                                        'allow_null' => 1,
                                        'multiple' => 0,
                                        'return_format' => 'value',
                                        'layout' => 'horizontal',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contact',
                                                ),
                                            ),
                                        ),
                                        'choices' => [
                                            'h1' => 'H1',
                                            'h2' => 'H2',
                                            'h3' => 'H3',
                                            'h4' => 'H4',
                                            'h5' => 'H5',
                                            'h6' => 'H6',
                                            'div' => 'DIV',
                                            'p' => 'P',
                                            'span' => 'SPAN',
                                        ],
                                        'default_value' => 'div',
                                    ],
                                    [
                                        'key' => '03_single_contact_textarea',
                                        'label' => 'Textarea',
                                        'name' => '03_single_contact_textarea',
                                        'type' => 'wysiwyg',
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contact',
                                                ),
                                            ),
                                        ),
                                        'default_value' => '',
                                    ],
                                    [
                                        'key' => '03_single_contact',
                                        'label' => 'Contact Form',
                                        'name' => '03_single_contact',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => '03_single_content_type',
                                                    'operator' => '==',
                                                    'value' => 'contact',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => [
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ],
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ],
                                ],
                            ],
                            [
                                'key' => '03_single_padding_topbottom',
                                'label' => 'Padding Top/Bottom',
                                'name' => '03_single_padding_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'padding0' => '0px',
                                    'padding20' => '20px',
                                    'padding40' => '40px',
                                    'padding60' => '60px',
                                    'padding80' => '80px',
                                    'padding100' => '100px',
                                    'padding120' => '120px',
                                    'padding160' => '160px',
                                    'padding200' => '200px',
                                ],
                                'default_value' => 'padding40',
                            ],
                            [
                                'key' => '03_single_margin_topbottom',
                                'label' => 'Margin Top/Bottom',
                                'name' => '03_single_margin_topbottom',
                                'type' => 'button_group',
                                'allow_null' => 1,
                                'multiple' => 0,
                                'return_format' => 'value',
                                'layout' => 'horizontal',
                                'wrapper' => [
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ],
                                'choices' => [
                                    'margin0' => '0px',
                                    'margin20' => '20px',
                                    'margin40' => '40px',
                                    'margin60' => '60px',
                                    'margin80' => '80px',
                                    'margin100' => '100px',
                                    'margin120' => '120px',
                                    'margin160' => '160px',
                                    'margin200' => '200px',
                                ],
                                'default_value' => 'margin40',
                            ],
                        ],
                    ],
                ],
                'button_label' => 'Nieuw blok',
                'min' => '',
                'max' => '',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-default-sidebar.php'
                ],
            ],
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'nieuws'
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ]);
endif;
