name: npm-install
on: [push, pull_request]
jobs:
  npm-install-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: npm install and build
      - run: |
          npm install
          npm run dev --if-present
        working-directory: wp-content/themes/defaulttheme/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            wp-content/themes/defaulttheme/dist