name: npm-install
on: [push]
jobs:
  npm-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./wp-content/themes/defaulttheme/
      - run: npm install
        working-directory: ./wp-content/themes/defaulttheme/